/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Point;
import javax.swing.JComponent;

/**
 *
 * @author Nick
 */
public class PigBrains extends javax.swing.JFrame {
    Grid gameGrid;
    Player player;
    int level=0;
    /**
     * Creates new form PigBrains
     */
    public PigBrains() {
        initComponents();
        Point a = new Point(0,0);
        player = new Player(a);
        gameGrid = new Grid();
        gameGrid.fillSpace(a);
        setGameText(gameGrid.display(player));
    }
    public void releaseTheBears(){
        if(level==0){
            Point a = new Point(3,3);
            Bear berry = new Bear(true,false,false,false,false,a);
            gameGrid.fillSpace(a);
        }
        if(level==1){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        moveDownB = new javax.swing.JButton();
        moveUpB = new javax.swing.JButton();
        moveLeftB = new javax.swing.JButton();
        moveRightB = new javax.swing.JButton();
        Turns = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GameText = new javax.swing.JTextArea();
        TurnsText = new javax.swing.JTextField();
        LevelText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        HelpMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SettingsMenu = new javax.swing.JMenuItem();
        CloseMenu = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moveDownB.setText("Move Down");
        moveDownB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownBActionPerformed(evt);
            }
        });

        moveUpB.setText("Move Up");
        moveUpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpBActionPerformed(evt);
            }
        });

        moveLeftB.setText("Move Left");
        moveLeftB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLeftBActionPerformed(evt);
            }
        });

        moveRightB.setText("Move Right");
        moveRightB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRightBActionPerformed(evt);
            }
        });

        Turns.setText("Turns");

        LevelLabel.setText("Level");

        GameText.setEditable(false);
        GameText.setColumns(20);
        GameText.setRows(5);
        GameText.setText("\n\n\n");
        jScrollPane1.setViewportView(GameText);

        TurnsText.setEditable(false);
        TurnsText.setText("0");

        LevelText.setEditable(false);
        LevelText.setText("0");

        jButton1.setText("Release The Bears");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        HelpMenu.setText("Help");
        jMenu1.add(HelpMenu);
        jMenu1.add(jSeparator1);

        SettingsMenu.setText("Settings");
        SettingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsMenuActionPerformed(evt);
            }
        });
        jMenu1.add(SettingsMenu);

        CloseMenu.setText("Close");
        CloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseMenuActionPerformed(evt);
            }
        });
        jMenu1.add(CloseMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Turns, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LevelText)
                                .addComponent(TurnsText, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                            .addGap(20, 20, 20))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(moveLeftB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveRightB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveDownB, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moveUpB, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Turns, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TurnsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moveUpB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveDownB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveLeftB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveRightB)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(126, 126, 126))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveUpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpBActionPerformed
        // TODO add your handling code here:
        setTurnText(incrementTurns(TurnsText.getText()));
        System.out.println("movedUP");
    }//GEN-LAST:event_moveUpBActionPerformed

    private void CloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseMenuActionPerformed
        // TODO add your handling code here:
     System.exit(0);
    }//GEN-LAST:event_CloseMenuActionPerformed

    private void SettingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsMenuActionPerformed

    private void moveDownBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownBActionPerformed
         setTurnText(incrementTurns(TurnsText.getText()));
        System.out.println("movedDown");
    }//GEN-LAST:event_moveDownBActionPerformed

    private void moveLeftBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLeftBActionPerformed
        setTurnText(incrementTurns(TurnsText.getText()));
        System.out.println("movedLeft");
    }//GEN-LAST:event_moveLeftBActionPerformed

    private void moveRightBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRightBActionPerformed
        setTurnText(incrementTurns(TurnsText.getText()));
        System.out.println("movedRight");
    }//GEN-LAST:event_moveRightBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        releaseTheBears();
    }//GEN-LAST:event_jButton1ActionPerformed
    public String incrementTurns(String a){
        int ac = Integer.parseInt(a);
        ++ac;
        String abs = Integer.toString(ac);
        return abs;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PigBrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PigBrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PigBrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PigBrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PigBrains().setVisible(true);
            }
        });
    }
    public boolean setGameText(String a){
        GameText.setText(a);
        if(GameText.getText().equals(a))return true;
        else return false;
    }
    public boolean setLevelText(String a){
        LevelText.setText(a);
        if(LevelText.getText().equals(a))return true;
        else return false;
    }
    public boolean setTurnText(String a){
        TurnsText.setText(a);
        if(TurnsText.getText().equals(a))return true;
        else return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CloseMenu;
    private javax.swing.JTextArea GameText;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JTextField LevelText;
    private javax.swing.JMenuItem SettingsMenu;
    private javax.swing.JLabel Turns;
    private javax.swing.JTextField TurnsText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton moveDownB;
    private javax.swing.JButton moveLeftB;
    private javax.swing.JButton moveRightB;
    private javax.swing.JButton moveUpB;
    // End of variables declaration//GEN-END:variables
}
